apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  source:
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 15.14.0
    chart: nginx
    helm:
      values: |
        # デプロイされるnamespacce
        namespaceOverride: "default"

        # デプロイされるコンテナイメージ
        image:
          registry: docker.io
          repository: bitnami/nginx
          tag: 1.25.4-debian-12-r3

        # レプリカ数
        replicaCount: 2

        # コンテナが公開するポート番号
        containerPorts:
          http: 8080

        # コンテナに割り当てるスペック
        resources:
          requests:
            cpu: 0.25
            memory: 128Mi
          limits:
            cpu: 2
            memory: 1024Mi

        # conf設定
        serverBlock: |-
          server {
            listen 0.0.0.0:8080;
            location / {
              return 200 "hello! \n";
            }
          }

        # Service設定
        service:
          ## @param service.type Service type
          ##
          type: NodePort
          ports:
            http: 8080
          nodePorts:
            http: 30080
          targetPort:
            http: http
